version: "3.3"

services:
  app:
    build:
      context: ./
    volumes:
      - .:/usr/src/dev-task
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0.24
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Europe/Berlin
    ports:
      - "3309:3306"
